### ISSUE TITLE
Add free Ghidra course from Hackaday

### ISSUE THREAD

**Issue by wrongbaud** [fkie-cad/awesome-embedded-and-iot-security#26]
Hackday and I have put together a free Ghidra course which can be seen here:

* https://hackaday.io/course/172292-introduction-to-reverse-engineering-with-ghidra
* [Github Repo](https://github.com/wrongbaud/hackaday-u)
* [Youtube Playlist](https://www.youtube.com/playlist?list=PL_tws4AXg7auglkFo6ZRoWGXnWL0FHAEi)

This may be worth adding to the list, let me know if you have any questions!

**Comment by rhelmke** [comment]
Hey wrongbaud, 

first of all thank you for putting together this free course :-). I think that looks like a nice addition to the list.

**Comment by 0xricksanchez** [comment]
I think the course contents are neat for beginners, and I do like the focus on Ghidra in general. However, I have to say that I don't see it being a good fit to an awesome list that purely focuses on embedded/IoT with the course being x86 exclusive.
